/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.ledger.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PostingEventProvided extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1912811999910654495L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PostingEventProvided\",\"namespace\":\"com.example.ledger.avro\",\"fields\":[{\"name\":\"postingId\",\"type\":\"long\"},{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"status\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PostingEventProvided> ENCODER =
      new BinaryMessageEncoder<PostingEventProvided>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PostingEventProvided> DECODER =
      new BinaryMessageDecoder<PostingEventProvided>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PostingEventProvided> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PostingEventProvided> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PostingEventProvided>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PostingEventProvided to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PostingEventProvided from a ByteBuffer. */
  public static PostingEventProvided fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long postingId;
  @Deprecated public long userId;
  @Deprecated public java.lang.CharSequence status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PostingEventProvided() {}

  /**
   * All-args constructor.
   * @param postingId The new value for postingId
   * @param userId The new value for userId
   * @param status The new value for status
   */
  public PostingEventProvided(java.lang.Long postingId, java.lang.Long userId, java.lang.CharSequence status) {
    this.postingId = postingId;
    this.userId = userId;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return postingId;
    case 1: return userId;
    case 2: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: postingId = (java.lang.Long)value$; break;
    case 1: userId = (java.lang.Long)value$; break;
    case 2: status = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'postingId' field.
   * @return The value of the 'postingId' field.
   */
  public java.lang.Long getPostingId() {
    return postingId;
  }

  /**
   * Sets the value of the 'postingId' field.
   * @param value the value to set.
   */
  public void setPostingId(java.lang.Long value) {
    this.postingId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.Long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Creates a new PostingEventProvided RecordBuilder.
   * @return A new PostingEventProvided RecordBuilder
   */
  public static com.example.ledger.avro.PostingEventProvided.Builder newBuilder() {
    return new com.example.ledger.avro.PostingEventProvided.Builder();
  }

  /**
   * Creates a new PostingEventProvided RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PostingEventProvided RecordBuilder
   */
  public static com.example.ledger.avro.PostingEventProvided.Builder newBuilder(com.example.ledger.avro.PostingEventProvided.Builder other) {
    return new com.example.ledger.avro.PostingEventProvided.Builder(other);
  }

  /**
   * Creates a new PostingEventProvided RecordBuilder by copying an existing PostingEventProvided instance.
   * @param other The existing instance to copy.
   * @return A new PostingEventProvided RecordBuilder
   */
  public static com.example.ledger.avro.PostingEventProvided.Builder newBuilder(com.example.ledger.avro.PostingEventProvided other) {
    return new com.example.ledger.avro.PostingEventProvided.Builder(other);
  }

  /**
   * RecordBuilder for PostingEventProvided instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PostingEventProvided>
    implements org.apache.avro.data.RecordBuilder<PostingEventProvided> {

    private long postingId;
    private long userId;
    private java.lang.CharSequence status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.ledger.avro.PostingEventProvided.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.postingId)) {
        this.postingId = data().deepCopy(fields()[0].schema(), other.postingId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PostingEventProvided instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.ledger.avro.PostingEventProvided other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.postingId)) {
        this.postingId = data().deepCopy(fields()[0].schema(), other.postingId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'postingId' field.
      * @return The value.
      */
    public java.lang.Long getPostingId() {
      return postingId;
    }

    /**
      * Sets the value of the 'postingId' field.
      * @param value The value of 'postingId'.
      * @return This builder.
      */
    public com.example.ledger.avro.PostingEventProvided.Builder setPostingId(long value) {
      validate(fields()[0], value);
      this.postingId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'postingId' field has been set.
      * @return True if the 'postingId' field has been set, false otherwise.
      */
    public boolean hasPostingId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'postingId' field.
      * @return This builder.
      */
    public com.example.ledger.avro.PostingEventProvided.Builder clearPostingId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.Long getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.example.ledger.avro.PostingEventProvided.Builder setUserId(long value) {
      validate(fields()[1], value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.example.ledger.avro.PostingEventProvided.Builder clearUserId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.example.ledger.avro.PostingEventProvided.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.example.ledger.avro.PostingEventProvided.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PostingEventProvided build() {
      try {
        PostingEventProvided record = new PostingEventProvided();
        record.postingId = fieldSetFlags()[0] ? this.postingId : (java.lang.Long) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.lang.Long) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PostingEventProvided>
    WRITER$ = (org.apache.avro.io.DatumWriter<PostingEventProvided>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PostingEventProvided>
    READER$ = (org.apache.avro.io.DatumReader<PostingEventProvided>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
